apiVersion: v1
kind: Service
metadata:
 name: lampservice
 labels:
  name: lamp
spec:
 ports:
 - port: 80
   nodePort: 30002
   protocol: TCP
 selector:
  app: lamp
 type: NodePort
---
apiVersion: v1
kind: Service
metadata:
 name: pythonservice
 labels:
  name: python
spec:
 ports:
 - port: 5000
   nodePort: 30005
   protocol: TCP
 selector:
  app: python
 type: NodePort